<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-18T14:05:16 IST" name="Default suite" finished-at="2023-06-18T14:05:20 IST" duration-ms="3465">
    <groups>
    </groups>
    <test started-at="2023-06-18T14:05:16 IST" name="Default test" finished-at="2023-06-18T14:05:20 IST" duration-ms="3465">
      <class name="org.learn.vtiger.testScripts.TS01_Login">
        <test-method is-config="true" signature="reportSetUp(java.lang.String)[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:16 IST" name="reportSetUp" finished-at="2023-06-18T14:05:16 IST" duration-ms="28" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[htmlReport]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 

at org.learn.vtiger.utility.Utility.getUtility(Utility.java:78)
at org.learn.vtiger.testScripts.BaseTest.reportSetUp(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSetUp -->
        <test-method is-config="true" signature="launch_hitUrl_SetUp(java.lang.String,java.lang.reflect.Method)[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:16 IST" name="launch_hitUrl_SetUp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1687077316989" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_hitUrl_SetUp -->
        <test-method signature="tc001_verifyLoginWithValidCredentials()[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:16 IST" name="tc001_verifyLoginWithValidCredentials" finished-at="2023-06-18T14:05:16 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 

at org.learn.vtiger.utility.Utility.getUtility(Utility.java:78)
at org.learn.vtiger.testScripts.BaseTest.reportSetUp(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc001_verifyLoginWithValidCredentials -->
        <test-method is-config="true" signature="Logout(org.testng.ITestResult)[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:17 IST" name="Logout" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1687077317008" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method is-config="true" signature="launch_hitUrl_SetUp(java.lang.String,java.lang.reflect.Method)[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:17 IST" name="launch_hitUrl_SetUp" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1687077317015" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_hitUrl_SetUp -->
        <test-method signature="tc002_verifyLoginWithInValidCredentials()[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:17 IST" name="tc002_verifyLoginWithInValidCredentials" finished-at="2023-06-18T14:05:17 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 

at org.learn.vtiger.utility.Utility.getUtility(Utility.java:78)
at org.learn.vtiger.testScripts.BaseTest.reportSetUp(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc002_verifyLoginWithInValidCredentials -->
        <test-method is-config="true" signature="Logout(org.testng.ITestResult)[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:17 IST" name="Logout" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1687077317032" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method signature="tc003LoginWithMultipleData()[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:17 IST" name="tc003LoginWithMultipleData" data-provider="TestData" finished-at="2023-06-18T14:05:20 IST" duration-ms="3312" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void org.learn.vtiger.testScripts.TS01_Login.tc003LoginWithMultipleData()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: tc003LoginWithMultipleData([])
Arguments: [(java.util.HashMap) {Sr No:=Sr No:, UserName=UserName, ErrorMsg=ErrorMsg, Password=Password, Scenario=Scenario}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.learn.vtiger.testScripts.TS01_Login.tc003LoginWithMultipleData()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: tc003LoginWithMultipleData([])
Arguments: [(java.util.HashMap) {Sr No:=Sr No:, UserName=UserName, ErrorMsg=ErrorMsg, Password=Password, Scenario=Scenario}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc003LoginWithMultipleData -->
        <test-method is-config="true" signature="flushReort()[pri:0, instance:org.learn.vtiger.testScripts.TS01_Login@7f0eb4b4]" started-at="2023-06-18T14:05:20 IST" name="flushReort" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1687077320513" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReort -->
      </class> <!-- org.learn.vtiger.testScripts.TS01_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
